FROM ubuntu:focal

RUN apt-get update && \
  apt-get -y install python3 python3-pip && \
  pip3 install requests requests_toolbelt && \
  mkdir /usr/src/boptest

ENV PYTHONPATH /usr/src/boptest
WORKDIR /usr/src/boptest

COPY project1-boptest/testcases /usr/src/boptest/testcases
COPY project1-boptest/service/provision/boptest_submit /usr/src/boptest/boptest_submit

CMD [ "python3", "-m", "boptest_submit", "--shared", "--path", "./testcases/"]
